### ISSUE TITLE
Central ticket for the new version of the dashboard

### ISSUE THREAD

**Issue by remcogerlich** [nens/flood-early-warning-interface#1]
### Introduction

A new version of the "Parramatta Dashboard" was discussed in cooperation with the customer, and then a UI design was made by Lirry:
- First version: https://xd.adobe.com/view/60585b94-db71-4089-bf21-0803942d8c74-350b/ 
- Current more detailed updated: https://xd.adobe.com/view/684396aa-6dcd-46ff-8378-72818fc15f1f-3d10/

Joeri will decide on functional issues, the main things is that where possible the functionality will stay the same as in the old dashboard, mutatis mutandis.

Technical decisions are made after discussion with Tom; this will be a React app, in Typescript, using React Query with a cache mechanism for backend communication. Re-usable components will be placed in a NenS React component library that I will start using [TSDX](https://tsdx.io/).

Real deadline is end of April, but realistically this must be done in February to prevent going out of budget.

TRS project is https://trs.nelen-schuurmans.nl/projects/7104/ .

### Requirements

In no particular order:

- There will still be an "iframe mode", but as there is no fullscreen tile anymore we need to decide what it will be
- "Mobile" needs to  be supported, in landscape mode
- Training mode must continue to work, probably need to fix the URLs used

**Comment by lexvand** [comment]
@remcogerlich Ik heb de half overkoepelende Floodsmart v2 Epic al gesloten (om richting archiveren van de parramatta-dashboard repo te werken). Kan deze ook afgesloten worden? Alle gerelateerde issues zijn klaar.

**Comment by remcogerlich** [comment]
Ja, dit is af.
