### ISSUE TITLE
To-do's charts

### ISSUE THREAD

**Issue by remcogerlich** [nens/flood-early-warning-interface#12]
[x] Units in legend are wrong, presumable colors and legendstrings too?
[x] Yellow block appears to be drawn in front of the lines
[x] Y-as rainfall vastzetten op 0-15 mm
[x] Tiles links moeten ook onclick hebben
[ ] Kruisje verdwijnt op mobiel
[ ] ~Kleuren worden anders, globaal configurabel maken~
[x] Minder functionaliteit kleine tiles
[x] Issue scrollen op mobiel per ongeluk de tile openen
[x] "View in Lizard link" back
[ ] Alarms in chart
[x] Add LGH to title of charts (see screendump below)

**Comment by joeriverheijden** [comment]
![image](https://user-images.githubusercontent.com/18265288/113389133-c8004780-938f-11eb-8a41-8866c7e70183.png)
