### ISSUE TITLE
Rainfall forecasts tab

### ISSUE THREAD

**Issue by remcogerlich** [nens/flood-early-warning-interface#18]
[x] Show rainfall totals WMS map from Geoserver; timestamp configurable in Leaflet thingy a la Klimaatatlas.
[x] Show popup when clicking on the map, uses Geoserver GetFeatureInfo
[x] Design storms information button

Not known:
- How to get information for legend

**Comment by joeriverheijden** [comment]
Header names for GetFeatureInfo table: 

·       Catchment name

·       Catchment Area

·       1hr total

·       3hr total

·       6hr total

·       12hr total

·       24hr total

·       48hr total

·       Forecast 3hr total

·       Forecast 6hr total

·       Forecast 12hr total

·       72hr max 6hr total
