### ISSUE TITLE
Parramatta CBD not clickable to graph 

### ISSUE THREAD

**Issue by joeriverheijden** [nens/flood-early-warning-interface#28]
![image.png](https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/077b2fb1-2304-49df-a69f-7084ed0dce1b)

**Comment by joeriverheijden** [comment]
@remcogerlich

**Comment by remcogerlich** [comment]
What this does is that it looks in the 'timeseries' properties of the warningArea, then finds a timeseries tile that has that timeseries UUID in it. If there is no such tile, nothing happens. So I think that is what is happening here, configuration problem.

**Comment by remcogerlich** [comment]
The UUID configured in the warning area is ce26f2e1-34c8-4fbb-abfa-204a06282f43 , which isn't used in any of the tiles, so this is correct.

It _is_ used in one of the tiles in 'publicTiles', but that isn't used anymore. Should probably be removed.

Not a bug.
