### ISSUE TITLE
Configuration of legend for historical forecasts doesn't work anymore

### ISSUE THREAD

**Issue by joeriverheijden** [nens/flood-early-warning-interface#29]
Added to list of colors:
https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/ec5b8fd6-3129-487d-a091-d70c60eaebab

Added to list of legend strings:
https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/36d090a6-b4cf-477f-9ea7-633063a9cb1c

Added historical forecasts to list:
https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/f31784b8-ee5d-43fc-bfac-bc445e9712b5

Legend result:
https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/972d196f-2101-4199-9e86-843dd35d7c5c

**Comment by joeriverheijden** [comment]
@remcogerlich

**Comment by remcogerlich** [comment]
Explained
