### ISSUE TITLE
Styling of historical forecasts in Parramatta CBD tile is different from the others. Seems to be flipped the other way around going from recent (light grey) to old (dark grey) instead of recent (dark grey) to old (light grey). 

### ISSUE THREAD

**Issue by joeriverheijden** [nens/flood-early-warning-interface#30]
This issue occurred after your most recent fix.

**Incorrect (Parramatta CBD) https://parramatta.lizard.net/floodsmart2/stations/16** :
https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/6d067245-c014-48e6-bb10-ba32764148ba

**Correct (Blacktown Creek) https://parramatta.lizard.net/floodsmart2/stations/5:**
https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/d6b93c62-7b4c-4476-a329-b61a09cbe6cd

**Comment by joeriverheijden** [comment]
@remcogerlich

**Comment by remcogerlich** [comment]
Which timeseries UUID do you expect to see in light gray? which in dark gray? In which tile?

**Comment by remcogerlich** [comment]
Fixed
