### ISSUE TITLE
[BLOCKED] Current version of clients findable within app

### ISSUE THREAD

**Issue by Derryrover** [nens/flood-early-warning-interface#31]
For example when you hoover over header you see current version of client.

See example pr here:
https://github.com/nens/frontend-tasks/issues/17#issuecomment-800984071

**Comment by Derryrover** [comment]
Draft version:
https://github.com/nens/flood-early-warning-interface/pull/37

**Comment by remcogerlich** [comment]
Correct, staging does not work as it does not have the data required for testing.

/floodsmart2/ is the only correct URL, /floodsmart/ is still the old Parramatta dashboard. Some point soon it will be decided that the app is sufficiently finished to replace the old one, then this will be deployed to /floodsmart/.

Thanks for implementing this, it was on my to do list!

**Comment by remcogerlich** [comment]
This is in production now and tested.
