### ISSUE TITLE
Be able to switch directly to another training scenario when user is already in a training scenario 

### ISSUE THREAD

**Issue by joeriverheijden** [nens/flood-early-warning-interface#32]
Current workflow for a user for going to another scenario when already in a scenario is the following: 

Click settings wheel > click leave training mode > select next training scenario 

Desired workflow when already in a scenario: 

Click settings wheel > select next training scenario 

![image.png](https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/f349d1a8-4a4b-4c68-827e-22bfdaf5a13f)

![image.png](https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/dd3bc4bf-1ac5-4676-bd9e-0c8e2d57027b)

**Comment by joeriverheijden** [comment]
@remcogerlich can you pick this up?

@Jonasvsl fyi

**Comment by remcogerlich** [comment]
Done
