### ISSUE TITLE
Add tile with measuring station to Stations & Graphs tab 

### ISSUE THREAD

**Issue by joeriverheijden** [nens/flood-early-warning-interface#34]
In the old dashboard there's a tile showing all measuring stations in the area. Chris would like this tile also in the new dashboard. 

Tile in old dashboard:
https://parramatta.lizard.net/floodsmart/full/5

Background maps for that tile: 

**River**
https://maps1.project.lizard.net/geoserver/v0227_parramatta_rainfall_db/wms?service=WMS&version=1.1.0&request=GetMap&layers=v0227_parramatta_rainfall_db:v0227_parramatta_river&styles=&bbox=309988.59375,6249516.5,322208.03125,6261953.0&width=754&height=768&srs=EPSG:28356&format=application/openlayers

**Creeks**
https://maps1.project.lizard.net/geoserver/v0227_parramatta_rainfall_db/wms?service=WMS&version=1.1.0&request=GetMap&layers=v0227_parramatta_rainfall_db:v0227_parramatta_creeks&styles=&bbox=1.6798104E7,-4012415.75,1.6818626E7,-3992929.25&width=768&height=729&srs=EPSG:3857&format=application/openlayers

**Parramatta LGA**
https://geoserver9.lizard.net/geoserver/parramatta/wms?service=WMS&version=1.1.0&request=GetMap&layers=parramatta:lga_parra&styles=&bbox=1.6782482801439825E7,-4030972.795372717,1.6842742297397397E7,-3945450.719373183&width=360&height=512&srs=EPSG:3857&format=application/openlayers

**Gauge Labels**
https://geoserver9.lizard.net/geoserver/parramatta/wms?service=WMS&version=1.1.0&request=GetMap&layers=parramatta:gauges&styles=&bbox=1.6797706364958998E7,-4006707.3087048447,1.6813514386408743E7,-3993794.0357961226&width=512&height=418&srs=EPSG:3857&format=application/openlayers

**Comment by remcogerlich** [comment]
Done.

The background maps can be configured in the 'wmsLayers' of the tile, they are now set to what they are in the old dashboard.

**Comment by joeriverheijden** [comment]
Thanks!
