### ISSUE TITLE
Make zoom steps in maps more gradual 

### ISSUE THREAD

**Issue by joeriverheijden** [nens/flood-early-warning-interface#35]
The zoom functionality on the map is quite strong. Can we make make the steps between zoomlevels slightly more gradual?

**Comment by remcogerlich** [comment]
We use the same default Leaflet functionality we use everywhere, also in the old site. I have no idea Leaflet has ways to tweak this. How much time do you want to spend on it?

**Comment by joeriverheijden** [comment]
Ok! Let's not touch it then.

**Comment by remcogerlich** [comment]
Won't do.
