### ISSUE TITLE
Make URL for iframe mode identical to the old floodsmart dashboard 

### ISSUE THREAD

**Issue by joeriverheijden** [nens/flood-early-warning-interface#36]
The URL for the iframe mode can be made identical to the old floodsmart dashboard iframe mode. When we switch from /floodsmart2 to /floodsmart the iframe on the website of the City Council will automatically be updated.

**Comment by remcogerlich** [comment]
I will try to see if I can get a redirect working. But it'd be much better if the website could just update the URL.

**Comment by joeriverheijden** [comment]
Ok. I will make sure that the URL is updated in the website.

**Comment by remcogerlich** [comment]
Presumably fixed.
