### ISSUE TITLE
Make Information modal configurable

### ISSUE THREAD

**Issue by remcogerlich** [nens/flood-early-warning-interface#60]
The text in the information modal should be configurable on the General tab (same one as the dashboard title).

There is a boolean 'showInfoModal' in the config, this is a simple checkbox.

Currently the HTML for the Info modal is completely hard coded in components/InfoModal.tsx.

The text to be shown should be editable in some sort of text area (Chakra TextArea?). How to deal with HTML is as yet undecided, it's important that all tags are escaped in the editor so the layout of the config pages aren't affected, but the text needs to be shown without escaping of course. Some sort of Markdown could also work? The HTML can be very simple.

It's possible that the whole problem doesn't show up when setting the textarea content from Javascript.

Images could be placed on "the projects share" (ask Lex) also, instead of committed in the repo, but for now that is no big issue.

**Comment by hoanphungt** [comment]
PR https://github.com/nens/flood-early-warning-interface/pull/63
