### ISSUE TITLE
Making Bounding Boxes configurable

### ISSUE THREAD

**Issue by remcogerlich** [nens/flood-early-warning-interface#65]
- We can't use the map draw component, as that makes a general polygon; this is purely minus and max values for lat and lon.

- The "default" bounding box is required, the others are optional (the default one is used if the specific one isn't set).

- Guess it should be on its own tab, or maybe we have more map-related settings.

**Comment by hoanphungt** [comment]
https://github.com/nens/flood-early-warning-interface/pull/68
