### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by remcogerlich** [nens/flood-early-warning-interface#8]

**Comment by Derryrover** [comment]
@remcogerlich 
@hoanphungt 

Maybe we soon can have a look at browser-testing tools like puppeteer.
Here is someone that made a chrome extension that generates a puppeteer script from a recording:
https://www.reddit.com/r/programming/comments/oogkvq/headless_recorder_is_a_chrome_extension_that/

The good thing is that these tests really test what a user would do (contrary to unit tests).
The bad thing is that in my previous job the intern that used a similar tool spend his every morning fixing failing tests.
